Repository globocom/secDevLabs, pull requests merged in 2019-06, with the labels that each got.

#255 Fix English typo within README files
  README.md
  owasp-top10-2017-apps/a1/copy-n-paste/README.md
  owasp-top10-2017-apps/a10/games-irados/README.md
  owasp-top10-2017-apps/a2/insecure-go-project/README.md
  owasp-top10-2017-apps/a2/saidajaula-monster/README.md
  owasp-top10-2017-apps/a3/snake-pro/README.md
  owasp-top10-2017-apps/a4/vinijr-blog/README.md
  owasp-top10-2017-apps/a5/ecommerce-api/README.md
  owasp-top10-2017-apps/a6/misconfig-wordpress/README.md
  owasp-top10-2017-apps/a6/stegonography/README.md
  owasp-top10-2017-apps/a7/gossip-world/README.md
  owasp-top10-2017-apps/a8/amarelo-designs/README.md
  owasp-top10-2017-apps/a9/cimentech/README.md
Labels: docs 📖

#258 Include a warning before the instruction to install ExploitDB
  owasp-top10-2017-apps/a6/misconfig-wordpress/README.md
  owasp-top10-2017-apps/a6/stegonography/README.md
  owasp-top10-2017-apps/a9/cimentech/README.md
Labels: docs 📖

#257 Check if user exists before registering
  owasp-top10-2017-apps/a5/ecommerce-api/app/db/queries.go
  owasp-top10-2017-apps/a5/ecommerce-api/app/handlers/session.go
Labels: A5-OWASP-2017, Vulnerable Ecommerce API, fix 🔧

#259 Add a Gitter chat badge to README.md
  README.md
Labels: enhancement 🚀
