Repository globocom/secDevLabs, pull requests merged in 2019-10, with the labels that each got.

#289 Fix link to menu 'Definition' on the README_Template.md
  docs/README_Template.md
Labels: docs 📖, fix 🔧

#291 Update secDevLabs logo
  README.md
  images/blinking-panda.gif
  images/panda-icon.png
  images/secDevLabs-logo.png
Labels: enhancement 🚀, hacktoberfest

#292 [FIX] Remove export from .env file
  owasp-top10-2017-apps/a5/ecommerce-api/app/scripts/generate-passwords.sh
Labels: bug 🕷, fix 🔧

#295 [A1] Fix SQL query example
  owasp-top10-2017-apps/a1/copy-n-paste/README.md
Labels: fix 🔧

#294 [A1] remove unnecessary localhost mention
  owasp-top10-2017-apps/a1/copy-n-paste/app/views/form.html
Labels: refact

#317 Upgrade in CSS standard
  owasp-top10-2017-apps/a9/cimentech/app/html/modules/dashboard/dashboard.css
Labels: Cimentech, enhancement 🚀

#341 Add the project's contribution scope
  docs/CONTRIBUTING.md
Labels: docs 📖, enhancement 🚀
