Repository globocom/secDevLabs, pull requests merged in 2019-02, with the labels that each got.

#72 Make A4 vulnerable again
  owasp-top10-2017-apps/a4/vinijr-blog/app/contact.php
Labels: bug 🕷

#73 [FEAT] Add new messages and remove-orphans into all Makefiles
  owasp-top10-2017-apps/a1/copy-n-paste/Makefile
  owasp-top10-2017-apps/a10/games-irados/Makefile
  owasp-top10-2017-apps/a2/saidajaula-monster/Makefile
  owasp-top10-2017-apps/a3/insecure-go-project/Makefile
  owasp-top10-2017-apps/a4/vinijr-blog/Makefile
  owasp-top10-2017-apps/a5/ecommerce-api/Makefile
  owasp-top10-2017-apps/a6/misconfig-wordpress/Makefile
  owasp-top10-2017-apps/a7/gossip-world/Makefile
  owasp-top10-2017-apps/a8/amarelo-designs/Makefile
  owasp-top10-2017-apps/a9/cimentech/Makefile
Labels: enhancement

#75 Add new secDevLabs logo and sections to README.md
  README.md
  images/secDevLabs-logo.png
Labels: docs 📖

#77 Update A6 attack narrative with new Burp images and brew install commands
  owasp-top10-2017-apps/a6/misconfig-wordpress/docs/ATTACK.md
  owasp-top10-2017-apps/a6/misconfig-wordpress/docs/attack10.png
  owasp-top10-2017-apps/a6/misconfig-wordpress/docs/attack11.png
  owasp-top10-2017-apps/a6/misconfig-wordpress/docs/attack12.png
  owasp-top10-2017-apps/a6/misconfig-wordpress/docs/attack13.png
Labels: docs 📖

#101 Add to A10 Burp instructions
  owasp-top10-2017-apps/a10/games-irados/docs/ATTACK.md
  owasp-top10-2017-apps/a10/games-irados/docs/attack10.png
  owasp-top10-2017-apps/a10/games-irados/docs/attack11.png
  owasp-top10-2017-apps/a10/games-irados/docs/attack9.png
Labels: docs 📖

#100 [Mitigation][A7] Remove safe filter so strings will be escaped
  owasp-top10-2017-apps/a7/gossip-world/app/templates/gossip.html
  owasp-top10-2017-apps/a7/gossip-world/app/templates/gossips.html
  owasp-top10-2017-apps/a7/gossip-world/app/templates/newgossip.html
Labels: A7-OWASP-2017, enhancement 🚀

#88 [A7] style: improve pep8 linting
  owasp-top10-2017-apps/a7/gossip-world/app/config.py
  owasp-top10-2017-apps/a7/gossip-world/app/model/db.py
  owasp-top10-2017-apps/a7/gossip-world/app/model/log.py
  owasp-top10-2017-apps/a7/gossip-world/app/model/password.py
  owasp-top10-2017-apps/a7/gossip-world/app/routes.py
  owasp-top10-2017-apps/a7/gossip-world/app/util/init_db.py
Labels: enhancement 🚀

#117 [DOCS] Add guidelines on how to install Dirb for Mac
  docs/Dirb.md
  docs/common.txt
  owasp-top10-2017-apps/a8/amarelo-designs/docs/ATTACK.md
  owasp-top10-2017-apps/a8/amarelo-designs/docs/attack2.png
Labels: enhancement 🚀

#132 [DOCS] Fix typo mistake
  owasp-top10-2017-apps/a9/cimentech/docs/ATTACK.md
Labels: A9-OWASP-2017, docs 📖

#107 [A2] style: improve code style
  owasp-top10-2017-apps/a2/saidajaula-monster/app/app.py
  owasp-top10-2017-apps/a2/saidajaula-monster/app/model/db.py
  owasp-top10-2017-apps/a2/saidajaula-monster/app/model/password.py
Labels: enhancement 🚀

#138 [DOCS] use python 3 for exploit code
  owasp-top10-2017-apps/a8/amarelo-designs/docs/ATTACK.md
Labels: docs 📖

#149 [DOCS] Update DOCS
  README.md
  owasp-top10-2017-apps/a3/snake-pro/README.md
  owasp-top10-2017-apps/a3/snake-pro/docs/ATTACK.md
  owasp-top10-2017-apps/a3/snake-pro/images/banner.png
Labels: docs 📖

#155 [DOCS] Add mitigation solution links
  README.md
  owasp-top10-2017-apps/a10/games-irados/README.md
  owasp-top10-2017-apps/a2/insecure-go-project/README.md
  owasp-top10-2017-apps/a2/saidajaula-monster/README.md
  owasp-top10-2017-apps/a3/snake-pro/README.md
  owasp-top10-2017-apps/a4/vinijr-blog/README.md
  owasp-top10-2017-apps/a5/ecommerce-api/README.md
  owasp-top10-2017-apps/a6/misconfig-wordpress/README.md
  owasp-top10-2017-apps/a8/amarelo-designs/README.md
  owasp-top10-2017-apps/a9/cimentech/README.md
Labels: docs 📖

#156 [DOCS] Adjust labels and mitigation solution links
  README.md
  owasp-top10-2017-apps/a1/copy-n-paste/README.md
  owasp-top10-2017-apps/a10/games-irados/README.md
  owasp-top10-2017-apps/a2/insecure-go-project/README.md
  owasp-top10-2017-apps/a2/saidajaula-monster/README.md
  owasp-top10-2017-apps/a3/snake-pro/README.md
  owasp-top10-2017-apps/a4/vinijr-blog/README.md
  owasp-top10-2017-apps/a5/ecommerce-api/README.md
  owasp-top10-2017-apps/a6/misconfig-wordpress/README.md
  owasp-top10-2017-apps/a7/gossip-world/README.md
  owasp-top10-2017-apps/a8/amarelo-designs/README.md
  owasp-top10-2017-apps/a9/cimentech/README.md
Labels: docs 📖

#114 Make initialization message check if app has successfully started
  owasp-top10-2017-apps/a1/copy-n-paste/Makefile
  owasp-top10-2017-apps/a1/copy-n-paste/deployments/check-init.sh
  owasp-top10-2017-apps/a10/games-irados/Makefile
  owasp-top10-2017-apps/a10/games-irados/deployments/check-init.sh
  owasp-top10-2017-apps/a2/insecure-go-project/Makefile
  owasp-top10-2017-apps/a2/insecure-go-project/deployments/check-init.sh
  owasp-top10-2017-apps/a2/insecure-go-project/deployments/docker-compose.yml
  owasp-top10-2017-apps/a2/saidajaula-monster/Makefile
  owasp-top10-2017-apps/a2/saidajaula-monster/deployments/check-init.sh
  owasp-top10-2017-apps/a3/snake-pro/Makefile
  owasp-top10-2017-apps/a3/snake-pro/deployments/check-init.sh
  owasp-top10-2017-apps/a4/vinijr-blog/Makefile
  owasp-top10-2017-apps/a4/vinijr-blog/deployments/check-init.sh
  owasp-top10-2017-apps/a5/ecommerce-api/Makefile
  owasp-top10-2017-apps/a5/ecommerce-api/deployments/check-init.sh
  owasp-top10-2017-apps/a6/misconfig-wordpress/Makefile
  owasp-top10-2017-apps/a6/misconfig-wordpress/deployments/check-init.sh
  owasp-top10-2017-apps/a7/gossip-world/Makefile
  owasp-top10-2017-apps/a7/gossip-world/deployments/check-init.sh
  owasp-top10-2017-apps/a8/amarelo-designs/Makefile
  owasp-top10-2017-apps/a8/amarelo-designs/deployments/check-init.sh
  owasp-top10-2017-apps/a9/cimentech/Makefile
  owasp-top10-2017-apps/a9/cimentech/deployments/check-init.sh
Labels: enhancement 🚀

#202 [FEAT] Redirect / to /login
  owasp-top10-2017-apps/a3/snake-pro/app/api/routes.go
  owasp-top10-2017-apps/a3/snake-pro/app/main.go
Labels: SnakePro, enhancement 🚀
